### ISSUE TITLE
Forked process still running after return

### ISSUE THREAD

**Issue by stepanhruda** [Zewo/Zewo#10]
I don't have any closer details right now, but it has happened on several occasion that the main process crashed and returned, but one of the forked processes kept running in the background.

This makes it hard to restart the server, because the port stays in use.

**Comment by lexrus** [comment]
You can kill these processes with:

``` bash
kill $(lsof -t -i:8080)

# If you're using fish-shell
kill (lsof -t -i:8080)
```
