### ISSUE TITLE
Not compiling in Xcode with 2016-05-03 toolchain: library not found: CURIParser

### ISSUE THREAD

**Issue by JohnCoates** [Zewo/Zewo#107]
Using `swift build` works fine, but when building in Xcode, I get the error `ld: library not found for -lCURIParser for architecture x86_64`

I've distilled the error a bit so it's reproducible. Anyone got any ideas?

Steps to reproduce:

```
git clone https://github.com/Zewo/URI.git
cd URI
# download depedencies
swift build --fetch
# build
xcodebuild TOOLCHAINS=org.swift.3020160503a -target URI
```

**Comment by JohnCoates** [comment]
Looking further into the issue, I believe the error stems from the modulemap.
Currently it's:

```
module CURIParser {
    header "uri_parser.h"
    link "CURIParser"
    export *
}
```

I believe that `link "CURIParser"` is not supposed to be there. As I understand it, that's for linking against installed libraries, and here I believe it's intended to be used self-referentially. Removing it solves this issue.

I'll be submitting a pull request

**Comment by Danappelxx** [comment]
Should be fixed now (thanks to you)

**Comment by JohnCoates** [comment]
Expanding on this further, I neglected to test an executable module with this. The URI module built fine, but when linking against an executable there's an error when using `swift build`.

I've been trying to make a modulemap that satisfies both `swift build` and Xcode through `swift build -X` but have been un-successful. Seems Xcode really doesn't like that directive, and any tutorials or documentation on modulemaps I've looked up consistently lack it.

I'm seeing that the swift-package-manager project itself [uses the `link` directive.](https://github.com/apple/swift-package-manager/blob/827b7033d1b11c083d174aad3b4887e333e3d8d9/Fixtures/ModuleMaps/Direct/CFoo/module.modulemap)  

It looks like soon a modulemap will not be needed for Xcode, and currently when omitted one is [synthesized](https://github.com/apple/swift-package-manager/pull/219) [automatically](https://github.com/apple/swift-evolution/blob/master/proposals/0038-swiftpm-c-language-targets.md) when using `swift build`.  https://bugs.swift.org/browse/SR-1450

Edit:
Found others with the same issue: https://github.com/IBM-Swift/Kitura/issues/463
Adding `${SRCROOT}/.build/debug` to Library Search Paths gets it to compile. Good enough workaround until Xcode projects generate correctly.

**Comment by mtso** [comment]
I followed the "Getting Started" instructions that build off of only `HTTPServer`, `Router` as dependencies. I then proceeded to run `swift package generate-xcodeproj` because `swift build -X` did not work for me in generating an Xcode project with Swift's "DEVELOPMENT-SNAPSHOT-2016-05-09-a".
~~The resulting generated Xcode project did not build correctly until I manually removed the self-referential `link` in the modulemaps for: `CURIParser`, `CHTTPParser`, and `CLibvenice`.~~

Edit: Oops, following @JohnCoates edit of adding `${SRCROOT}/.build/debug` did the trick.

**Comment by Danappelxx** [comment]
For now the search path workaround is fine, though it relies on the c libraries being built under `.build/debug` already. I added a note about this to the readme, hopefully this gets resolved one way or another on the SPM side.

Thanks @mtso for bringing this back up :)
