### ISSUE TITLE
Update all Zewo modules to the new 07-25 snapshot

### ISSUE THREAD

**Issue by Danappelxx** [Zewo/Zewo#120]
The plan:
- All dependencies pointed at `0.10` (with the exception of Open-Swift/S4, which should be pointed at `0.11`)
- The version in the README updated to `majorVersion: 0, minor: 10`
- The badge in the README updated to 0.10 (i.e. [![this badge](https://img.shields.io/badge/Zewo-0.10-FF7565.svg?style=flat)](https://img.shields.io/badge/Zewo-0.10-FF7565.svg?style=flat))
- Once the branch satisfies the requirements, a pull request is to be created (merging into master, obviously)
- Build and run the tests locally, and fix any warnings or errors
- Create a new tag `0.10.0`

List of relevant repositories:
- [ ] [Zewo/Zewo](https://github.com/Zewo/Zewo)
- [ ] [Zewo/Router](https://github.com/Zewo/Router)
- [ ] [Zewo/HTTP](https://github.com/Zewo/HTTP)
- [ ] [Zewo/Mustache](https://github.com/Zewo/Mustache)
- [ ] [Zewo/Sideburns](https://github.com/Zewo/Sideburns)
- [ ] [Zewo/JSON](https://github.com/Zewo/JSON)
- [ ] [Zewo/JSONMediaType](https://github.com/Zewo/JSONMediaType)
- [ ] [Zewo/MediaType](https://github.com/Zewo/MediaType)
- [ ] [Zewo/HTTPSerializer](https://github.com/Zewo/HTTPSerializer)
- [ ] [Zewo/URI](https://github.com/Zewo/URI)
- [ ] [Zewo/CURIParser](https://github.com/Zewo/CURIParser)
- [ ] [Zewo/HTTPParser](https://github.com/Zewo/HTTPParser)
- [ ] [Zewo/CHTTPParser](https://github.com/Zewo/CHTTPParser)
- [ ] [Zewo/OpenSSL](https://github.com/Zewo/OpenSSL)
- [ ] [Zewo/COpenSSL](https://github.com/Zewo/COpenSSL)
- [ ] [Zewo/SQL](https://github.com/Zewo/SQL)
- [ ] [Zewo/PostgreSQL](https://github.com/Zewo/PostgreSQL)
- [ ] [Zewo/CLibpq](https://github.com/Zewo/CLibpq)
- [ ] [Zewo/MySQL](https://github.com/Zewo/MySQL)
- [ ] [Zewo/CMySQL](https://github.com/Zewo/CMySQL)
- [ ] [Zewo/WebSocket](https://github.com/Zewo/WebSocket)
- [ ] [Zewo/WebSocketClient](https://github.com/Zewo/WebSocketClient)
- [ ] [Zewo/WebSocketServer](https://github.com/Zewo/WebSocketServer)
- [ ] [Zewo/EngineIOServer](https://github.com/Zewo/EngineIOServer)
- [ ] [Zewo/BasicAuthMiddleware](https://github.com/Zewo/BasicAuthMiddleware)
- [ ] [Zewo/Base64](https://github.com/Zewo/Base64)
- [ ] [Zewo/POSIXRegex](https://github.com/Zewo/POSIXRegex)
- [x] [Zewo/POSIX](https://github.com/Zewo/POSIX)
- [x] [Zewo/String](https://github.com/Zewo/String)
- [ ] [Zewo/TrieRouteMatcher](https://github.com/Zewo/TrieRouteMatcher)
- [ ] [Zewo/StructuredData](https://github.com/Zewo/StructuredData)
- [ ] [Zewo/Log](https://github.com/Zewo/Log)
- [ ] [Zewo/LogMiddleware](https://github.com/Zewo/LogMiddleware)
- [ ] [Zewo/URLEncodedForm](https://github.com/Zewo/URLEncodedForm)
- [ ] [Zewo/ContentNegotiationMiddleware](https://github.com/Zewo/ContentNegotiationMiddleware)
- [ ] [Zewo/RegexRouteMatcher](https://github.com/Zewo/RegexRouteMatcher)
- [ ] [Zewo/Redis](https://github.com/Zewo/Redis)
- [ ] [Zewo/Event](https://github.com/Zewo/Event)
- [x] [Zewo/XML](https://github.com/Zewo/XML)
- [x] [Zewo/CLibXML2](https://github.com/Zewo/CLibXML2)
- [ ] [Zewo/PathParameterMiddleware](https://github.com/Zewo/PathParameterMiddleware)
- [ ] [Zewo/Mapper](https://github.com/Zewo/Mapper)
- [ ] [Zewo/RecoveryMiddleware](https://github.com/Zewo/RecoveryMiddleware)
- [ ] [Zewo/BranchMiddleware](https://github.com/Zewo/BranchMiddleware)
- [ ] [Zewo/Resource](https://github.com/Zewo/Resource)
- [ ] [Zewo/RedirectMiddleware](https://github.com/Zewo/RedirectMiddleware)
- [ ] [Zewo/URLEncodedFormMediaType](https://github.com/Zewo/URLEncodedFormMediaType)
- [ ] [Zewo/UUID](https://github.com/Zewo/UUID)
- [ ] [Zewo/SessionMiddleware](https://github.com/Zewo/SessionMiddleware)
- [ ] [Zewo/TodoBackend](https://github.com/Zewo/TodoBackend)
- [ ] [Zewo/Reflection](https://github.com/Zewo/Reflection)
- [ ] [Zewo/CUUID](https://github.com/Zewo/CUUID)
- [x] [Zewo/zlib](https://github.com/Zewo/zlib)
- [x] [Zewo/gzip](https://github.com/Zewo/gzip)
- [x] [VeniceX/Venice](https://github.com/VeniceX/Venice)
- [x] [VeniceX/CLibvenice](https://github.com/VeniceX/CLibvenice)
- [ ] [VeniceX/ChannelStream](https://github.com/VeniceX/ChannelStream)
- [ ] [VeniceX/IP](https://github.com/VeniceX/IP)
- [ ] [VeniceX/TCP](https://github.com/VeniceX/TCP)
- [ ] [VeniceX/HTTPServer](https://github.com/VeniceX/HTTPServer)
- [ ] [VeniceX/HTTPClient](https://github.com/VeniceX/HTTPClient)
- [x] [VeniceX/File](https://github.com/VeniceX/File)
- [ ] [VeniceX/HTTPFile](https://github.com/VeniceX/HTTPFile)
- [ ] [VeniceX/UDP](https://github.com/VeniceX/UDP)
- [ ] [VeniceX/TCPSSL](https://github.com/VeniceX/TCPSSL)
- [ ] [VeniceX/HTTPSServer](https://github.com/VeniceX/HTTPSServer)
- [ ] [VeniceX/HTTPSClient](https://github.com/VeniceX/HTTPSClient)

**Comment by czechboy0** [comment]
Looking at that list, I'm sure we could script most of the work described above. Maybe automatically: 1. switch to master, 2. pull, 3. make sure clean git status, 4. create and switch to branch 3.0-preview-1, 5. switch .swift-version, 6. swift build --clean=dist, 7. swift build, 8. swift test, then human will check no warnings, errors, test failures and finish each repo up? There needs to be a better way going forward then doing all these manually one by one :)

**Comment by Danappelxx** [comment]
Great idea! Once we resolve the [swiftenv issue](https://github.com/kylef/swiftenv/issues/37) we'll work on that :)

**Comment by Lidbetter** [comment]
On July 5th, 2016 preview 2 was released, is that now the intended goal?

**Comment by Danappelxx** [comment]
@Lidbetter There are a number of issues with the previews. We're probably going to adopt the next development snapshot that comes out (after 06/20), though right now we're busy with Quark :)

**Comment by Danappelxx** [comment]
@czechboy0 could you check off the repositories which you updated? Thanks!

**Comment by czechboy0** [comment]
@Danappelxx Done, I also checked off the ones that didn't need any update to work with 07-25 (so no new release was made).

I didn't change the badges, but I think the readme changes should be made in bulk with a script, it's easy to forget one (badge and dependency line for Package.swift).

**Comment by Danappelxx** [comment]
This is not the workflow we're going to use. Instead, we're going to work with a monolith at zewo/flux and update from there.
