### ISSUE TITLE
[HTTPClient] Client fails when Content-Length is not set

### ISSUE THREAD

**Issue by paulofaria** [Zewo/Zewo#130]
When HTTP response doesn't set Content-Length, http and https client raises and closedStream(0 bytes) error.
It should calculate total length read till the end of http server connection, when this header is not set.

How to reproduce? 

For this response:

```
HTTP/1.1 200 OK
Date: Fri, 16 Sep 2016 16:23:17 GMT
Connection: close

test
```

Run on the simplest http server (https://gist.github.com/vi4m/a3809caea5e4a59d27e1032f8b9657f1) 

And with this swift client code:

```

import HTTPClient

do {
    let c = try Client(url: "http://localhost:9000")
    let request = Request(method: .get, url: "/")
    var response = try c.request(request!)
}
catch {
    print(error)
    print("Failed.")
    exit(2)
}
print("Success.")

```

it will fail with closedStream(0 bytes error).

When the response is completed with "Content-Lenght: 5" http request works fine.

> Created by @vi4m

**Comment by vi4m** [comment]
We can close it now, already fixed.

**Comment by Danappelxx** [comment]
Great!

**Comment by Danappelxx** [comment]
Looks like it's back...

**Comment by vi4m** [comment]
https://github.com/Zewo/HTTP/pull/25

**Comment by Danappelxx** [comment]
Could you resubmit your pr's on Zewo/Zewo please? The idea is that you do all the development in one place and push out the changes to the other repositories. For more information [see here](https://github.com/Zewo/Zewo/blob/master/Docs/WORKFLOW.md).

**Comment by vi4m** [comment]
yeah, sure.
