### ISSUE TITLE
[HTTPClient] More flexibility with the default headers

### ISSUE THREAD

**Issue by paulofaria** [Zewo/Zewo#138]
I'm trying use the HTTPClient to connect to a server that requires me to sign the requests (including the headers). 
Since HTTPClient adds some default headers when it makes the request, I can't access them to include them into the signature.
It'd be great to expose them in some way.

Thanks!

> @0xpablo

@0xpablo hmm. you need to sign all headers?

> @paulofaria

I'm afraid so :(
Look at the AWS documentation: http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

Add the canonical headers, followed by a newline character. The canonical headers consist of a list of all the HTTP headers that you are including with the signed request.

> @0xpablo

**Comment by paulofaria** [comment]
@0xpablo I think you can sign all headers using a middleware. Something like this.

``` swift
struct SignMiddleware : Middleware {
    func respond(to request: Request, chainingTo next: Responder) throws -> Response {
        var request = request
        // sign the headers using request.headers
        return try next.respond(to: request)
    }
}

let client = try Client(url: "api.com")
let sign = SignMiddleware()

let request = try Request(...)
let response = try client.request(request, middleware: [sign])
```

Are you working on an AWS client? That's on our roadmap. 😊

**Comment by 0xpablo** [comment]
Thanks for the suggestion! I completely ignored the Middleware API 😅, I will try it out.

About the AWS client, I'm trying to use some actions of the SNS service, so I'm not planning to write a full client. Still, hit me up if I can be of any help when you start with the client.
