### ISSUE TITLE
[HTTP] If the HTTP message has `Content-Length` we should allocate the body buffer beforehand

### ISSUE THREAD

**Issue by paulofaria** [Zewo/Zewo#141]
Right now.. we get data from the parser callback and append.

https://github.com/Zewo/Zewo/blob/master/Modules/HTTP/Sources/HTTP/Parser/RequestParser.swift#L141

We should reserve the bytes, so the append operation doesn't cost as much.

**Comment by robertjpayne** [comment]
@paulofaria I think this is a bad idea, easy way for someone to destroy the server with a malicious Content-Length. New request parser is much more efficient anyways.
