### ISSUE TITLE
[IO] Implement Worker

### ISSUE THREAD

**Issue by robertjpayne** [Zewo/Zewo#170]
Single threaded programs are easiest to make but we need to be mindful some codebases may struggle to ensure they don't block the main thread when using 3rd party libraries like ZeroMQ.

Passing data across threads is _safe_ with libmill but libmill isn't threadsafe so we must suspend the coroutine and awake it when the worker task is finished…

Here's a very rough implementation:

```
func worker<T>(closure: @escaping (Void) throws -> T) throws -> T {
    var reader: unixsock?
    var writer: unixsock?
    unixpair(&reader, &writer)
    let fd = unixdetach(writer)
    var result: T! = nil
    var resultError: Swift.Error? = nil

    DispatchQueue.global().async {
        do {
            result = try closure()
        } catch {
            resultError = error
        }

        let flags = fcntl(fd, F_GETFL)
        _ = fcntl(fd, F_SETFL, flags & ~O_NONBLOCK)

        var done: Byte = 0
        send(fd, &done, 1, 0)
    }
    var byte: Byte = 0
    _ = unixrecv(reader!, &byte, 1, -1)
    unixclose(reader!)

    guard resultError == nil else {
        throw resultError!
    }
    return result
}
```

**Comment by robertjpayne** [comment]
As bad as this looks it actually works _really_ well. I tested heavily tonight serialising JSON on a background thread and was shocked I didn't crash anything.

We should discourage workers over multi-process setups but it may help us when trying to integrate non-Zewo compatible API's (e.g. URLSession that supports all of libcurl.)

**Comment by vovasty** [comment]
actually I got crash when running several tasks (macOS 10.12)

```
Resource temporarily unavailable (src/signaler.cpp:301)
Resource temporarily unavailable (src/signaler.cpp:301)
Resource temporarily unavailable (src/signaler.cpp:301)
Assert failed: crp->in (/Users/i843418/Documents/AramZamZam/prankster/Packages/CLibvenice-0.14.0/Sources/kqueue.inc:267)
```
