### ISSUE TITLE
SHA1 is calculated incorrectly in zewo/Websocket

### ISSUE THREAD

**Issue by JimiSmith** [Zewo/Zewo#186]
The SHA1 sum is calculated incorrectly when opening a web socket. This causes the websocket to fail to open on at least Chrome

Attempt to open a websocket connection to a zewo websocket server from chrome - the socket connection will fail with the following message: WebSocket connection to 'ws://localhost:8080/socket failed: Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value

The error is in the arrayOfBytes function in SHA1.swift. I replaced the implementation of that with the one from [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift/blob/13764570021ca73c315c3de18f367e5fdb55d785/Sources/CryptoSwift/Generics.swift#L38) and that resolved the issue. I'm happy to submit a pull request with this change if needed?

**Comment by Danappelxx** [comment]
Yes, please do submit a pull request! Looks like we broke it during the update to Swift 3.

**Comment by Danappelxx** [comment]
Just noticed the PR you submitted - awesome! Could you submit it to this repository on the `websocket` branch? That's [how we do our development](https://github.com/Zewo/Zewo/blob/master/Docs/WORKFLOW.md).

**Comment by JimiSmith** [comment]
Sure. No problem :)

**Comment by JimiSmith** [comment]
Done. Thanks for the help @Danappelxx
