### ISSUE TITLE
[Reflection] Segmentation Fault, Swift Reflection

### ISSUE THREAD

**Issue by hikelee** [Zewo/Zewo#199]
# Segmentation Fault of Swift Reflection

I recently use swift reflection to convert json string to a struct, but got "Segmentation Fault" in runtime. As the test code is too much to write here, I committed my test code in github, can you help have a look, thanks.
## Steps to reproduce

$uname -a
    Linux dev 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux 

$ swift --version
    Swift version 3.0 (swift-3.0.1-PREVIEW-1)
    Target: x86_64-unknown-linux-gnu

$ git clone https://github.com/hikelee/SegmentationFault.git

$ cd SegmentationFault

$ swift build
    Cloning https://github.com/Zewo/Reflection.git
    HEAD is now at 2bc1a76 make mappable tests public on reflection
    Resolved version: 0.14.0
    Compile Swift Module 'Reflection' (23 sources)
    Compile Swift Module 'Main' (1 sources)
    Linking ./.build/debug/Main

$ .build/debug/Main
    Person(firstName: "James")
    Person(firstName: "James")
    Person(firstName: "James")
    Person(firstName: "James")
    ------
    Person(firstName: "James")
    Person(firstName: "pb?\0\0\0\0\0a")
    Person(firstName: "\u{10}\u{10}\0a")
    Segmentation fault

**Comment by Danappelxx** [comment]
Related to #195.

Thanks for the bug report. We're already tracking this and hope to resolve it soon. For now, you can implement `init(map:)` manually.

**Comment by hikelee** [comment]
there are some special characters printed out,please resolve it together,tks

**Comment by Danappelxx** [comment]
Oh, this is in a non-venice environment, I didn't see that initially. This changes things @bradhilton

**Comment by hikelee** [comment]
Got a different error message running in arch linux :
 Hello: /tmp/yaourt-tmp-hike/aur-swift/src/swift/include/swift/Runtime/../../../stdlib/public/SwiftShims/RefCount.h:252: bool StrongRefCount::doDecrementShouldDeallocate() [ClearPinnedFlag = false]: Assertion `newval + quantum >= RC_ONE && "releasing reference with a refcount of zero"' failed.
Person(firstName: Aborted (core dumped)

**Comment by bradhilton** [comment]
@hikelee Can you try running it again using `Reflection 0.14.1`? I just issued a fix to #195, which may also fix this issue since that turned out to be an problem with C strings which may apply to your example as well.

**Comment by hikelee** [comment]
@bradhilton ,thanks for tracking, but the bug still exists. Below is my test result:

Arch Linux test
$swift build
    Cloning https://github.com/Zewo/Reflection.git
    HEAD is now at e75ca32 Remove @testable from PublicTests
    Resolved version: 0.14.1
    Compile Swift Module 'Reflection' (24 sources)
    Compile Swift Module 'Main' (1 sources)
    Linking ./.build/debug/Main
$ .build/debug/Main
    Person(firstName: "James")
    Person(firstName: "James")
    Person(firstName: "James")
    Person(firstName: "James")
    ------
    Person(firstName: "James")
    Main: /tmp/yaourt-tmp-hike/aur-swift/src/swift/include/swift/Runtime/../../../stdlib/public/SwiftShims/RefCount.h:252: bool StrongRefCount::doDecrementShouldDeallocate() [ClearPinnedFlag = false]: Assertion `newval + quantum >= RC_ONE && "releasing reference with a refcount of zero"' failed.
    Person(firstName: Aborted (core dumped)

Ubuntu 16.04 test:
$swift build
    Cloning https://github.com/Zewo/Reflection.git
    HEAD is now at e75ca32 Remove @testable from PublicTests
    Resolved version: 0.14.1
    Compile Swift Module 'Reflection' (24 sources)
    Compile Swift Module 'Main' (1 sources)
    Linking ./.build/debug/Main
$ .build/debug/Main
    Person(firstName: "James")
    Person(firstName: "James")
    Person(firstName: "James")
    Person(firstName: "James")
    ------
    Person(firstName: "James")
    Person(firstName: "pâÜ\u{01}\0\0\0\0a")
    Person(firstName: "\u{10}\u{10}\0a")
    Segmentation fault

**Comment by hikelee** [comment]
There is no error in macOS, seems it's only appears in linux environments

**Comment by bradhilton** [comment]
Thanks @hikelee, I'll have to try debugging it in linux then.
