### ISSUE TITLE
[HTTPServer] Ambiguous use of 'get(_:middleware:respond:)' with Integer as parameter

### ISSUE THREAD

**Issue by joernroeder** [Zewo/Zewo#202]
I'm getting a `Ambiguous use of 'get(_:middleware:respond:)'` error after i've updated a route to: 

``` swift
route.get("/foo/:bar") { (request, bar: Int) in
```

I think it's ambiguous cause `Int` is matching the route definitions for `MapInitializable` as well as `PathParameterConvertible`
- https://github.com/Zewo/HTTPServer/blob/master/Sources/HTTPServer/Router/Routes.swift#L49
- https://github.com/Zewo/HTTPServer/blob/master/Sources/HTTPServer/Router/Routes.swift#L91

**Comment by joernroeder** [comment]
@Danappelxx just a reminder too. We've discussed this on slack today…

**Comment by Danappelxx** [comment]
Hmm thats logically ambiguous too, actually. Is bar supposed to be from the path parameters or from the request body? We need some way to distinguish this.

cc @paulofaria

**Comment by paulofaria** [comment]
@joernroeder IIRC this used to work before. We can change the signature for the body version from:

``` swift
public func get<
    T: MapInitializable
    >(
    _ path: String = "",
    middleware: [Middleware] = [],
    content: T.Type = T.self,
    respond: @escaping (Request, T) throws -> Response
) {
    add(method: .get, path: path, middleware: middleware, respond: respond)
}
```

to

``` swift
public func get<
    T: MapInitializable
    >(
    _ path: String = "",
    middleware: [Middleware] = [],
    content: T.Type,
    respond: @escaping (Request, T) throws -> Response
) {
    add(method: .get, path: path, middleware: middleware, respond: respond)
}
```

Basically remove the default parameter from `content`. This way we can do stuff like this:

``` swift
route.get("/foo/:bar") { (request, bar: Int) in … }
route.post("/foo", content: Bar.self) { (request, bar) in … }
route.post("/foo/:bar", content: Baz.self) { (request, bar: Int, baz) in … }
```

What do you guys think?
