### ISSUE TITLE
[PostgreSQL] Obtaining Null values from varchar/text columns in DB results in Optional("") being returned

### ISSUE THREAD

**Issue by Cyfirr** [Zewo/Zewo#211]
# Optional("") returned where nil is expected

Based on TodoBackend project (https://github.com/Zewo/TodoBackend) I did very similar PSQL store for my project. When my model contains String? fields replicating the null-allowed text or varchar columns in DB, if I insert nil values when writing it to DB I expect the nil values to be returned by the get methods as well. DB correctly has NULL values in it, but values returned by get(id) or getAll() methods are Optional("") instead of nil.

## Steps to reproduce

1. Create a model having the String? fields and corresponding table in DB having text or varchar fields which can be NULLs.
2. In your tests / main / whatever executable source file instantiate your model and assign *nil* values to fields of type String?.
3. Insert the record using the model and store.insert(model) method.
4. Save the value returned by insert into a variable.
5. Compare model object created by you and model returned by insert within the PersistedEntity.

Expected: nil values are nil values in both and comparison succeeds.
Actual: nil values were replaced by Optional("")

My code:
```swift
func testAssetInsertion() throws {
    let original = Asset(id: "bc_id", name: "Test", frontCover: nil, data: nil, type: nil) 
    let inserted = try store.insertAsset(asset: original)
    XCTAssertEqual(inserted.model, original)
    let retrieved = try store.getAsset(id: "bc_id")
    XCTAssertEqual(retrieved!.model, original)
    let retrievedThroughGetAll = try store.getAllAssets()
    XCTAssertEqual(retrievedThroughGetAll.count, 1)
    XCTAssertEqual(retrievedThroughGetAll[0].model, original)
}
```

Test results:
```
/home/anatoli/workspace/StorageService/Tests/StorageLayerTests/PostgreSQLEBooksStore/PostgreSQLEBooksStoreTests.swift:45: error: PostgreSQLEBooksStoreTests.testAssetInsertion : XCTAssertEqual failed: ("Asset(id: "bc_id", name: "Test", frontCover: Optional(""), data: Optional(""), type: Optional(""))") is not equal to ("Asset(id: "bc_id", name: "Test", frontCover: nil, data: nil, type: nil)") - 
/home/anatoli/workspace/StorageService/Tests/StorageLayerTests/PostgreSQLEBooksStore/PostgreSQLEBooksStoreTests.swift:47: error: PostgreSQLEBooksStoreTests.testAssetInsertion : XCTAssertEqual failed: ("Asset(id: "bc_id", name: "Test", frontCover: Optional(""), data: Optional(""), type: Optional(""))") is not equal to ("Asset(id: "bc_id", name: "Test", frontCover: nil, data: nil, type: nil)") - 
/home/anatoli/workspace/StorageService/Tests/StorageLayerTests/PostgreSQLEBooksStore/PostgreSQLEBooksStoreTests.swift:50: error: PostgreSQLEBooksStoreTests.testAssetInsertion : XCTAssertEqual failed: ("Asset(id: "bc_id", name: "Test", frontCover: Optional(""), data: Optional(""), type: Optional(""))") is not equal to ("Asset(id: "bc_id", name: "Test", frontCover: nil, data: nil, type: nil)")
```

* I have implementation of insert and model very close to what is in TodoStore and related sources.
So I expect it to be reproducible there.
If not - please let me know and I will add more info.

**Comment by Danappelxx** [comment]
Reproduced, looking into it now. Thanks for the thorough bug report!

**Comment by Danappelxx** [comment]
Fixed in https://github.com/Zewo/PostgreSQL/commit/c009b1848c1a7e796d10e5be32e88031861f043d, tagged 0.14.1. Try `swift build --clean=dist` and running the project again!

**Comment by Cyfirr** [comment]
Verified for the case:
let original = Asset(id: "bc_id", name: "Test", frontCover: nil, data: nil, type: nil)
However, if I will change the inserted entity to 
let original = Asset(id: "bc_id", name: "Test", frontCover: "", data: "", type: "")
Then test will fail. DB should have an empty string in my opinion and empty string should be returned by the ORM.
/home/anatoli/workspace/StorageService/Tests/StorageLayerTests/PostgreSQLEBooksStore/PostgreSQLEBooksStoreTests.swift:45: error: PostgreSQLEBooksStoreTests.testAssetInsertion : XCTAssertEqual failed: ("Asset(id: "bc_id", name: "Test", frontCover: nil, data: nil, type: nil)") is not equal to ("Asset(id: "bc_id", name: "Test", frontCover: Optional(""), data: Optional(""), type: Optional(""))") - 
/home/anatoli/workspace/StorageService/Tests/StorageLayerTests/PostgreSQLEBooksStore/PostgreSQLEBooksStoreTests.swift:47: error: PostgreSQLEBooksStoreTests.testAssetInsertion : XCTAssertEqual failed: ("Asset(id: "bc_id", name: "Test", frontCover: nil, data: nil, type: nil)") is not equal to ("Asset(id: "bc_id", name: "Test", frontCover: Optional(""), data: Optional(""), type: Optional(""))") - 
/home/anatoli/workspace/StorageService/Tests/StorageLayerTests/PostgreSQLEBooksStore/PostgreSQLEBooksStoreTests.swift:50: error: PostgreSQLEBooksStoreTests.testAssetInsertion : XCTAssertEqual failed: ("Asset(id: "bc_id", name: "Test", frontCover: nil, data: nil, type: nil)") is not equal to ("Asset(id: "bc_id", name: "Test", frontCover: Optional(""), data: Optional(""), type: Optional(""))") 

So, probably a bit better distinguish is required between NULL and ""...

**Comment by Danappelxx** [comment]
Reminder for self - need to add a check using `PQgetisnull`

**Comment by Danappelxx** [comment]
Okay, _really_ fixed this time. https://github.com/Zewo/PostgreSQL/commit/a3dbab5f63e834d111fa0ec5f6a33b5797abcfa8 @0.14.3
