### ISSUE TITLE
Using swift concurrency library

### ISSUE THREAD

**Issue by ghost** [Zewo/Zewo#223]
# Using swift concurrency library

Author: [Pyros2097](https://github.com/pyros2097)

## Description
Using the swift Safe https://github.com/tidwall/Safe Library for concurrency

## Why

I was just thinking libmill is a native dependency and provides the concurrency constructs as go. But his library Safe https://github.com/tidwall/Safe has implemented these constructs in swift. It would ease builds and maybe/maybe not improve performance.

**Comment by Danappelxx** [comment]
There are a few reasons why abandoning libmill in favor of Safe is not 1 for 1 trade and as such not a great idea. I'll explain more as soon as possible, but don't have the time right now.

**Comment by wiwiwa** [comment]
The `Safe` library is not a coroutine library. It provides an elegant way to start and use a new thread.

Am I right?

**Comment by tidwall** [comment]
@wiwiwa You're right. `Safe` does not have coroutines. Just a simple `dispatch` call that wraps around a thread.
