### ISSUE TITLE
[HTTPClient] "Too many open files" error

### ISSUE THREAD

**Issue by donut** [Zewo/Zewo#228]
# Too many open files

After making X number of requests to a specific URL, the following code results in a "Too many open files" error. The error is thrown on `client.get()`.

```swift
let client = try Client(url: url)
_ = try client.get(url.absoluteString)
```

## Steps to reproduce

1. `$ swiftenv local 3.0.2`
2. `$ swift package init --type executable`
3. `$ vim Package.swift`:
    ```swift
    import PackageDescription

    let package = Package(
      name: "HTTPClient_TooManyOpenFiles",
      dependencies: [
         .Package(url: "https://github.com/Zewo/HTTPClient.git",
                  majorVersion: 0, minor: 14),
      ]
    )
    ```
4. `$ vim Sources/main.swift`:
    ```swift
    import Foundation
    import HTTPClient

    var counter = 0
    let url = URL(string: "https://static.rightthisminute.com/goomba/EogVZIHg.json")!

    print("[GET \(url.absoluteString)]")

    while true {
      counter += 1
      print(counter, separator: "", terminator: "; ")
      let client: Client

      do {
        /// I tried moving this code so that the same client is re-used. However,
        /// this resulted in the connecting being closed on the 1001st attempt.
        /// Specifically, `Axis.StreamError.closedStream` is thrown.
        client = try Client(url: url)
      } catch {
        print("\nFailed initializing client on attempt \(counter).")
        debugPrint(error)
        break
      }

      do {
        _ = try client.get(url.absoluteString)
      } catch {
        print("\nFailed GET request on attempt \(counter).")
        debugPrint(error)
        break
      }
    }
    ```
5. `$ swift build`
6. `$ ./.build/debug/HTTPClient_TooManyOpenFiles`

On a DigitalOcean $5/mo Ubuntu 16.04 droplet (512MB RAM, created specifically for this purpose) it fails consistently at the 1019th attempt. On my late-2013 Retina 15" MacBook Pro with 16GB of RAM it fails around the 5500th attempt. Before it fails on macOS, it slowly consumes more and more RAM. But usually errors out before 30 MB usage.

**Comment by vi4m** [comment]
Yeah, I confirm this issue too.

**Comment by vzsg** [comment]
Also steadily reproduced here.

With some Xcode debugging, I found that the following line is leaking malloc blocks: https://github.com/Zewo/TCP/blob/master/Sources/TCP/TCPStream.swift#L23

And it seems that every call to get creates two TCP connections, of which only one is cleaned up. Checking the process with `lsof` also confirms this, TCP connections are left open like no tomorrow.
