### ISSUE TITLE
Usage in iOS projects?

### ISSUE THREAD

**Issue by gazialankus** [Zewo/Zewo#257]
The [cocoapods docs](https://cocoapods.org/pods/Venice#user-content-manually) have outdated instructions for iOS, because there is no Venice.xcodeproj in this repo. 

The pod won't work with Xcode 9.3 since it's Swift 2.

So, I guess we need to create an Xcode proj and compile the latest code here to use it in iOS, does that sound right? Could you let me know about what's the easiest way to get started with Venice in iOS?

**Comment by unnamedd** [comment]
As far as I know, @paulofaria didn't create Zewo and related projects to be used in iOS, they are more focused on a server side, but if you want to try, the way to create is this used in screenshot. 
<img width="703" alt="image" src="https://user-images.githubusercontent.com/83694/39291590-d23eb6d6-4933-11e8-94bd-e04c2397f7d6.png">

and after create the .xcodeproj, you will need to import it into your project. I don't know if it will work, but you can try.
