### ISSUE TITLE
Redefinition of module 'Incandescence'

### ISSUE THREAD

**Issue by davidask** [Zewo/Zewo#3]
Keep getting this error after following the Carthage instructions and trying to build the project, embedding the frameworks that Carthage produces. 

```
/Users/davidask/Work/Projects/Project/Source/Carthage/Checkouts/Luminescence/Dependencies/module.modulemap:1:8: error: redefinition of module 'Incandescence'
module Incandescence [system] {
       ^
/Users/davidask/Work/Projects/Project/Source/Carthage/Checkouts/Epoch/Carthage/Checkouts/Luminescence/Dependencies/module.modulemap:1:8: note: previously defined here
module Incandescence [system] {
       ^
<unknown>:0: error: could not build Objective-C module 'Incandescence'
```

Any info on this? Perhaps i've misunderstood the installation instructions.

**Comment by paulofaria** [comment]
Yeah. I tried it in my computer from work and got the same thing. The cocoapods instructions seems to be working fine. You can try that while I investigate this issue. I'm thinking it's a carthage problem.

**Comment by davidask** [comment]
Alright, great. I can confirm that the CocoaPods way works well. Thanks!

**Comment by paulofaria** [comment]
I'm gonna keep this open until I figure it out! Thanks, man!
