### ISSUE TITLE
Update Swift version badge in READMEs.

### ISSUE THREAD

**Issue by Danappelxx** [Zewo/Zewo#61]
We're supporting Swift 3, so we should update the Swift 2.2 badges to Swift 3 badges. Some repositories already have this (ex: this one), but others (ex, [Zewo/PostgreSQL](https://github.com/zewo/postgresql)), need fixing.

**Comment by FreeMasen** [comment]
Submitted pull requests for:
Base64
CLibq
CLibpq-OSX
CLibXML2
COpenSSL
COpenSSL-OSX
CZeroMQ
generator-zewo
HTTPJSON
OpenSSL
PostgreSQL
READMEGenerator
Sideburns
Swift-Command-Line-Application-Template

**Comment by antonmes** [comment]
@FreeMasen awesome, thank you! merged :metal:
