### ISSUE TITLE
Fix bug in router where composing routers with similar routers can lead to them being overridden

### ISSUE THREAD

**Issue by Danappelxx** [Zewo/Zewo#68]
For example, with the following code:

``` swift
let router1 = Router { route in
     route.get("/path") { _ in return Response() }
}
let router2 = Router { route in
     route.post("/path") { _ in return Response() }
}
let mainRouter = Router {
    route.compose(router: router1)
    route.compose(router: router2)
}
```

`GET /path` will go through, but `POST /path` will return `405 Method not allowed` because router1 is not taking the routes from router2 into account.

We have to brainstorm how to solve this - the obvious solution is to propagate up the routes when composing routers and ignoring the matchers of the composed routers, but this is not a good solution for obvious reasons.

**Comment by paulofaria** [comment]
I think the fix would be just a matter of checking if a route with a given path already exists and then append the actions to the existing route.

**Comment by Danappelxx** [comment]
Turns out this was actually not a bug... The code I was using to trigger it had its own issues. I wrote a test in Zewo/Router just in case so this issue can be closed now.
