### ISSUE TITLE
[HTTPClient] leaks memory in `Client.init()` and `client.get()`

### ISSUE THREAD

**Issue by donut** [Zewo/Zewo#71]
[Gist](https://gist.github.com/donut/4f09366d036539942ea9bf7be614574e)

In the following example, every 10 seconds `Client()` leaks about 0.9 MB and `Client.get()` leaks about 0.1 MB. 

``` swift
import HTTPSClient
import Venice
​
let YouTubeAPIKey = ""
let id = "FLTNU6m2Mk"
let path = "/youtube/v3/videos?part=snippet,statistics"
         + "&id=\(id)&key=\(YouTubeAPIKey)"
​
every(10.seconds) { _ in
    var response: Response
    do {
      let client = try Client(host: "www.googleapis.com", port: 443) // leaks ~0.9 MB
      response = try client.get(path) // leaks ~0.1 MB
      print("Whoo hoo")
    } catch {
      print("Failed retreiving stats from YouTube API: \(error)")
    }
}
​
let infiniteCaffeine = Channel<Int>()
infiniteCaffeine.receive()
```

**Comment by Danappelxx** [comment]
While this is obviously not going to fix the memory leak, I would still like to note that the `Client` should be initialized outside of the `every`, and only `.get` should be called inside it.

**Comment by Danappelxx** [comment]
Correct me if I'm wrong, but wasn't this confirmed to be the coroutine stack increasing its size (and not an actual memory leak)?

**Comment by donut** [comment]
No, [that was for `JSONParse().parse()`](https://github.com/Zewo/Zewo/issues/72). Maybe it applies to this, but in the case of `JSONParse` it was a much smaller memory increase every time around. Also, I've let it run for hours and seen the memory usage get into the hundreds of megs, approaching 1GB. According to the issue, the coroutine cache hits a limit at 64 caches. This definitely increases beyond that many times.

**Comment by donut** [comment]
Looks like this may have been fixed with https://github.com/Zewo/OpenSSL/pull/15

**Comment by donut** [comment]
That pull request did fix a large portion of the leak, but I'm still seeing a continuous increase in memory. I updated the test project to work with 05-03-a and 0.7.X version of `Venice` and `HTTPSClient` and let it run for about 3.5 hours. It started with 3.3 MB usage and gradually increased to 9.9 MB usage.

``` swift
import HTTPSClient
import Venice

let YouTubeAPIKey = ""
let id = "FLTNU6m2Mk"
let path = "/youtube/v3/videos?part=snippet,statistics"
         + "&id=\(id)&key=\(YouTubeAPIKey)"

every(10.seconds) { _ in
  var response: Response
  do {
    let client = try Client(uri: "https://www.googleapis.com:443")
    response = try client.get(path)
    print("Whoo hoo")
  } catch {
    print("Failed retreiving stats from YouTube API: \(error)")
  }
}

let infiniteCaffeine = Channel<Int>()
infiniteCaffeine.receive()
```
