### ISSUE TITLE
[HTTPFile] cause chunk encoding error

### ISSUE THREAD

**Issue by donut** [Zewo/Zewo#80]
When I deliver a certain file using `HTTPFile.FileResponder` along with either `HTTPSServer` or `HTTPServer`, it always fails delivering the whole file. Chrome reports "net:ERR_INVALID_CHUNKED_ENCODING" in its Developer Tools Network tab. 

In [this gist](https://gist.github.com/donut/b86494e9b5a24a1c33830df730d3093d) you can see react.js file as delivered by nginx or `HTTPServer`. The page is super long, so it may be easier to open up the files in new tabs:
- [Delivered via HTTPServer](https://gist.githubusercontent.com/donut/b86494e9b5a24a1c33830df730d3093d/raw/42c6eb31fd089ee589951856d962f4c78c0574cf/react.via_HTTPServer.js) (Cuts off on line 1485)
- [Delivered via nginx](https://gist.githubusercontent.com/donut/b86494e9b5a24a1c33830df730d3093d/raw/42c6eb31fd089ee589951856d962f4c78c0574cf/react.via_nginx.js) (delivers whole file)

I think I have experienced this occasionally on OS X, but it happens consistently on my 512 MB DigitalOcean VM running Ubuntu 14.04.3.

**Comment by donut** [comment]
This seems to happen as file size increases.

**Comment by donut** [comment]
@Danappelxx was able to help me out. It looks like the issue lies within the response being a `FileStream`. Replacing the `FileStream` body with `file.read()` resolves the issue.

[Conversation on slack](https://zewo.slack.com/archives/help/p1461347709000385)

**Comment by Danappelxx** [comment]
Issue has not been resolved yet.

**Comment by paulofaria** [comment]
> Replacing the FileStream body with file.read() resolves the issue.

That was misleading, haha. so what's left?

**Comment by Danappelxx** [comment]
Well, FileStream is still broken (and hence HTTPFile), so that needs to be fixed. The workaround that I suggested to @donut was to recreate HTTPFile but use File instead of FileStream, which is not a good overall solution.

**Comment by paulofaria** [comment]
Why is `FileStream` still broken? It's not like it was before.

**Comment by paulofaria** [comment]
Did anybody test?

**Comment by Danappelxx** [comment]
Sorry, I meant that we haven't fixed it yet (hence why this issue should remain open).
