### ISSUE TITLE
Hello World Build instructions failed

### ISSUE THREAD

**Issue by iamcam** [Zewo/Zewo#82]
I could be missing something, but going through the _getting started_ instructions in the Readme left me with a compile error. After some trial and error, I believe either the instructions are wrong with regard to the swift package that should be used.

> Then we install Swift Development Snapshot from February 8, 2016.

```
swiftenv install DEVELOPMENT-SNAPSHOT-2016-04-12-a
swiftenv local DEVELOPMENT-SNAPSHOT-2016-04-12-a
```

Indeed, installing `DEVELOPMENT-SNAPSHOT-2016-04-12-a` causes the compile crash, but changing it to the Feb 8 snapshot allows me to compile the Hello World demo.

Was another snapshot date intended for `swiftenv` newer than Feb 8? Or is there something else going on here?

**Comment by Danappelxx** [comment]
Hello! Which version of Zewo are you trying to use? 0.5 uses the 04-12 snapshot, while 0.3 uses the 02-08 snapshot. 0.5 just came out recently so we haven't updated our docs yet (but that's happening soon!).

**Comment by iamcam** [comment]
Thanks for the quick response! Ah, that would make sense. It looks like I was still using 0.3. Updating to 0.5 and following the listed swiftenv versions works great.

**Comment by paulofaria** [comment]
@iamcam any further trouble you can reach us on [slack.zewo.io](slack.zewo.io) 😊
