### ISSUE TITLE
URLEncodedFormParser does not support empty values

### ISSUE THREAD

**Issue by drewag** [Zewo/Zewo#86]
The current parsing of URL Encoded data does not support when a value is posted as empty. For example:

```
email=user%40example.com&password=&password_confirmation=
```

This throws a `malformedURLEncodedForm` error. Instead, it should return three values (`["email": "user@example.com", "password": "", "password_confirmation":""]`), two of which are empty strings.

**Comment by drewag** [comment]
If I am using something incorrectly, please let me know. If not, I would be happy to submit a pull request to fix this problem.

**Comment by paulofaria** [comment]
@drewag Yeah, you're right! That's the expected behaviour. Would be awesome if you sent a PR.
