### ISSUE TITLE
[HTTPClient] Cannot send requests with >=5k of data in body

### ISSUE THREAD

**Issue by aal80** [Zewo/Zewo#87]
The problem occurs with HTTPSClient package (https://github.com/VeniceX/HTTPSClient).

Client is unable to send a request (POST/PUT) with over 5k of data in body. To reproduce:

``` swift
let client = try Client(uri: "https://httpbin.org")
let body = Data.buffer(with: 5_000)
let response = try client.put("/put", body:body)
print(response)

```

Note that after reducing body size to <=4k requests are successfully sent.

**Comment by Danappelxx** [comment]
Will be fixed once [this pr](https://github.com/Zewo/Zewo/pull/174) is merged (tested with 500kb).
