### ISSUE TITLE
.startInBackground() not work ?

### ISSUE THREAD

**Issue by kiokumicu** [Zewo/Zewo#9]
Hi!
I try start server with .startInBackground(), but it's not work and no errors.
What am I doing wrong ?

**Comment by paulofaria** [comment]
`startInBackground()` starts the server in a coroutine. If you don't have any other call that blocks after `startInBackground()` the server will exit. You should only call `startInBackground` when you have two servers running in the same applications like in the [example](https://github.com/Zewo/Examples/blob/master/Sources/Todo/main.swift). If you have only one server you sould just call `start()`.

**Comment by kiokumicu** [comment]
Thanks!
